name: CYOAP release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@main
        with:
          node-version: 'latest'
      - run: npm install

      - run: npm run build

      - run: mkdir ./dist/dist

      - run: |
          7z a dist/cyoap_vue_${{ github.ref_name }}.zip ./dist/*

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          files: |
            dist/cyoap_vue_${{ github.ref_name }}.zip
