name: CYOAP release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: '19.8.1'
      - run: npm install

      - run: npm run build

      - run: mkdir ./dist/dist

      - run: |
          $version= "${{ github.ref_name }}".replace('v', '')
          7z a dist/cyoap_vue_$version.zip ./dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/cyoap_vue_$version.zip
